// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * Get backlog user with API Key
 * @param {string} apiKey
 * @returns {Promise<string> & { cancel(): void }}
 */
export function GetUser(apiKey) {
    let $resultPromise = /** @type {any} */($Call.ByID(267984116, apiKey));
    return $resultPromise;
}

/**
 * Hide window
 * @returns {Promise<void> & { cancel(): void }}
 */
export function HideWindow() {
    let $resultPromise = /** @type {any} */($Call.ByID(1520192101));
    return $resultPromise;
}

/**
 * Open URL in default browser
 * @param {string} url
 * @returns {Promise<void> & { cancel(): void }}
 */
export function OpenURL(url) {
    let $resultPromise = /** @type {any} */($Call.ByID(2058785194, url));
    return $resultPromise;
}

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Run() {
    let $resultPromise = /** @type {any} */($Call.ByID(3968766394));
    return $resultPromise;
}
